swagger: "2.0"
info:
    title: Arduino Create Agent
    description: "A companion of Arduino Create. \n\tAllows the website to perform operations on the user computer, \n\tsuch as detecting which boards are connected and upload sketches on them."
    version: ""
host: localhost:80
basePath: /v2
consumes:
    - application/json
    - plain/text
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /pkgs/indexes:
        get:
            tags:
                - indexes
            summary: list indexes
            operationId: indexes#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Pariatur laudantium inventore qui.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/IndexesListInvalidURLResponseBody'
            schemes:
                - http
    /pkgs/indexes/add:
        post:
            tags:
                - indexes
            summary: add indexes
            operationId: indexes#add
            parameters:
                - name: AddRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/IndexesAddRequestBody'
                    required:
                        - url
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/IndexesAddResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/IndexesAddInvalidURLResponseBody'
            schemes:
                - http
    /pkgs/indexes/delete:
        post:
            tags:
                - indexes
            summary: remove indexes
            operationId: indexes#remove
            parameters:
                - name: RemoveRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/IndexesRemoveRequestBody'
                    required:
                        - url
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/IndexesRemoveResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/IndexesRemoveInvalidURLResponseBody'
            schemes:
                - http
    /pkgs/tools/available:
        get:
            tags:
                - tools
            summary: available tools
            operationId: tools#available
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ToolsToolResponseCollection'
            schemes:
                - http
    /pkgs/tools/installed:
        get:
            tags:
                - tools
            summary: installed tools
            operationId: tools#installed
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ToolsToolResponseCollection'
            schemes:
                - http
        post:
            tags:
                - tools
            summary: install tools
            operationId: tools#install
            parameters:
                - name: InstallRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ToolsInstallRequestBody'
                    required:
                        - name
                        - version
                        - packager
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ToolsInstallResponseBody'
            schemes:
                - http
    /pkgs/tools/installed/{packager}/{name}/{version}:
        delete:
            tags:
                - tools
            summary: remove tools
            operationId: tools#remove
            parameters:
                - name: packager
                  in: path
                  description: The packager of the tool
                  required: true
                  type: string
                - name: name
                  in: path
                  description: The name of the tool
                  required: true
                  type: string
                - name: version
                  in: path
                  description: The version of the tool
                  required: true
                  type: string
                - name: RemoveRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ToolsRemoveRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ToolsRemoveResponseBody'
            schemes:
                - http
definitions:
    IndexesAddInvalidURLResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: url invalid (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    IndexesAddRequestBody:
        title: IndexesAddRequestBody
        type: object
        properties:
            url:
                type: string
                description: The url of the index file
                example: https://downloads.arduino.cc/packages/package_index.json
        example:
            url: https://downloads.arduino.cc/packages/package_index.json
        required:
            - url
    IndexesAddResponseBody:
        title: 'Mediatype identifier: application/vnd.arduino.operation; view=default'
        type: object
        properties:
            status:
                type: string
                description: The status of the operation
                example: ok
        description: AddResponseBody result type (default view)
        example:
            status: ok
        required:
            - status
    IndexesListInvalidURLResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: url invalid (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    IndexesRemoveInvalidURLResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: url invalid (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    IndexesRemoveRequestBody:
        title: IndexesRemoveRequestBody
        type: object
        properties:
            url:
                type: string
                description: The url of the index file
                example: https://downloads.arduino.cc/packages/package_index.json
        example:
            url: https://downloads.arduino.cc/packages/package_index.json
        required:
            - url
    IndexesRemoveResponseBody:
        title: 'Mediatype identifier: application/vnd.arduino.operation; view=default'
        type: object
        properties:
            status:
                type: string
                description: The status of the operation
                example: ok
        description: RemoveResponseBody result type (default view)
        example:
            status: ok
        required:
            - status
    ToolResponse:
        title: 'Mediatype identifier: application/vnd.arduino.tool; view=default'
        type: object
        properties:
            name:
                type: string
                description: The name of the tool
                example: bossac
            packager:
                type: string
                description: The packager of the tool
                example: arduino
            version:
                type: string
                description: The version of the tool
                example: 1.7.0-arduino3
        description: A tool is an executable program that can upload sketches. (default view)
        example:
            name: bossac
            packager: arduino
            version: 1.7.0-arduino3
        required:
            - name
            - version
            - packager
    ToolsInstallRequestBody:
        title: ToolsInstallRequestBody
        type: object
        properties:
            checksum:
                type: string
                description: "A checksum of the archive. Mandatory when url is present. \n\tThis ensures that the package is downloaded correcly."
                example: SHA-256:1ae54999c1f97234a5c603eb99ad39313b11746a4ca517269a9285afa05f9100
            name:
                type: string
                description: The name of the tool
                example: bossac
            packager:
                type: string
                description: The packager of the tool
                example: arduino
            signature:
                type: string
                description: |-
                    The signature used to sign the url. Mandatory when url is present.
                    	This ensure the security of the file downloaded
                example: 382898a97b5a86edd74208f10107d2fecbf7059ffe9cc856e045266fb4db4e98802728a0859cfdcda1c0b9075ec01e42dbea1f430b813530d5a6ae1766dfbba64c3e689b59758062dc2ab2e32b2a3491dc2b9a80b9cda4ae514fbe0ec5af210111b6896976053ab76bac55bcecfcececa68adfa3299e3cde6b7f117b3552a7d80ca419374bb497e3c3f12b640cf5b20875416b45e662fc6150b99b178f8e41d6982b4c0a255925ea39773683f9aa9201dc5768b6fc857c87ff602b6a93452a541b8ec10ca07f166e61a9e9d91f0a6090bd2038ed4427af6251039fb9fe8eb62ec30d7b0f3df38bc9de7204dec478fb86f8eb3f71543710790ee169dce039d3e0
            url:
                type: string
                description: "The url where the package can be found. Optional. \n\tIf present checksum must also be present."
                example: http://downloads.arduino.cc/tools/bossac-1.7.0-arduino3-linux64.tar.gz
            version:
                type: string
                description: The version of the tool
                example: 1.7.0-arduino3
        example:
            checksum: SHA-256:1ae54999c1f97234a5c603eb99ad39313b11746a4ca517269a9285afa05f9100
            name: bossac
            packager: arduino
            signature: 382898a97b5a86edd74208f10107d2fecbf7059ffe9cc856e045266fb4db4e98802728a0859cfdcda1c0b9075ec01e42dbea1f430b813530d5a6ae1766dfbba64c3e689b59758062dc2ab2e32b2a3491dc2b9a80b9cda4ae514fbe0ec5af210111b6896976053ab76bac55bcecfcececa68adfa3299e3cde6b7f117b3552a7d80ca419374bb497e3c3f12b640cf5b20875416b45e662fc6150b99b178f8e41d6982b4c0a255925ea39773683f9aa9201dc5768b6fc857c87ff602b6a93452a541b8ec10ca07f166e61a9e9d91f0a6090bd2038ed4427af6251039fb9fe8eb62ec30d7b0f3df38bc9de7204dec478fb86f8eb3f71543710790ee169dce039d3e0
            url: http://downloads.arduino.cc/tools/bossac-1.7.0-arduino3-linux64.tar.gz
            version: 1.7.0-arduino3
        required:
            - name
            - version
            - packager
    ToolsInstallResponseBody:
        title: 'Mediatype identifier: application/vnd.arduino.operation; view=default'
        type: object
        properties:
            status:
                type: string
                description: The status of the operation
                example: ok
        description: InstallResponseBody result type (default view)
        example:
            status: ok
        required:
            - status
    ToolsRemoveRequestBody:
        title: ToolsRemoveRequestBody
        type: object
        properties:
            checksum:
                type: string
                description: "A checksum of the archive. Mandatory when url is present. \n\tThis ensures that the package is downloaded correcly."
                example: SHA-256:1ae54999c1f97234a5c603eb99ad39313b11746a4ca517269a9285afa05f9100
            signature:
                type: string
                description: |-
                    The signature used to sign the url. Mandatory when url is present.
                    	This ensure the security of the file downloaded
                example: 382898a97b5a86edd74208f10107d2fecbf7059ffe9cc856e045266fb4db4e98802728a0859cfdcda1c0b9075ec01e42dbea1f430b813530d5a6ae1766dfbba64c3e689b59758062dc2ab2e32b2a3491dc2b9a80b9cda4ae514fbe0ec5af210111b6896976053ab76bac55bcecfcececa68adfa3299e3cde6b7f117b3552a7d80ca419374bb497e3c3f12b640cf5b20875416b45e662fc6150b99b178f8e41d6982b4c0a255925ea39773683f9aa9201dc5768b6fc857c87ff602b6a93452a541b8ec10ca07f166e61a9e9d91f0a6090bd2038ed4427af6251039fb9fe8eb62ec30d7b0f3df38bc9de7204dec478fb86f8eb3f71543710790ee169dce039d3e0
            url:
                type: string
                description: "The url where the package can be found. Optional. \n\tIf present checksum must also be present."
                example: http://downloads.arduino.cc/tools/bossac-1.7.0-arduino3-linux64.tar.gz
        example:
            checksum: SHA-256:1ae54999c1f97234a5c603eb99ad39313b11746a4ca517269a9285afa05f9100
            signature: 382898a97b5a86edd74208f10107d2fecbf7059ffe9cc856e045266fb4db4e98802728a0859cfdcda1c0b9075ec01e42dbea1f430b813530d5a6ae1766dfbba64c3e689b59758062dc2ab2e32b2a3491dc2b9a80b9cda4ae514fbe0ec5af210111b6896976053ab76bac55bcecfcececa68adfa3299e3cde6b7f117b3552a7d80ca419374bb497e3c3f12b640cf5b20875416b45e662fc6150b99b178f8e41d6982b4c0a255925ea39773683f9aa9201dc5768b6fc857c87ff602b6a93452a541b8ec10ca07f166e61a9e9d91f0a6090bd2038ed4427af6251039fb9fe8eb62ec30d7b0f3df38bc9de7204dec478fb86f8eb3f71543710790ee169dce039d3e0
            url: http://downloads.arduino.cc/tools/bossac-1.7.0-arduino3-linux64.tar.gz
    ToolsRemoveResponseBody:
        title: 'Mediatype identifier: application/vnd.arduino.operation; view=default'
        type: object
        properties:
            status:
                type: string
                description: The status of the operation
                example: ok
        description: RemoveResponseBody result type (default view)
        example:
            status: ok
        required:
            - status
    ToolsToolResponseCollection:
        title: 'Mediatype identifier: application/vnd.arduino.tool; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ToolResponse'
        description: AvailableResponseBody is the result type for an array of ToolResponse (default view)
        example:
            - name: bossac
              packager: arduino
              version: 1.7.0-arduino3
            - name: bossac
              packager: arduino
              version: 1.7.0-arduino3
            - name: bossac
              packager: arduino
              version: 1.7.0-arduino3
            - name: bossac
              packager: arduino
              version: 1.7.0-arduino3
