openapi: 3.0.3
info:
    title: Arduino Create Agent
    description: "A companion of Arduino Create. \n\tAllows the website to perform operations on the user computer, \n\tsuch as detecting which boards are connected and upload sketches on them."
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for arduino-create-agent
paths:
    /v2/pkgs/indexes:
        get:
            tags:
                - indexes
            summary: list indexes
            operationId: indexes#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Rerum et soluta laudantium.
                                example:
                                    - Et deserunt.
                                    - Impedit iusto libero explicabo.
                                    - Dolor adipisci nulla.
                                    - Quam voluptas voluptates expedita rem ipsum.
                            example:
                                - Dignissimos consectetur eos molestiae culpa soluta deserunt.
                                - Nobis sint dolorem unde.
                                - Quia doloremque.
                                - Atque iusto tempore sit quod dolor repellat.
                "400":
                    description: 'invalid_url: url invalid'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /v2/pkgs/indexes/add:
        post:
            tags:
                - indexes
            summary: add indexes
            operationId: indexes#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            url: https://downloads.arduino.cc/packages/package_index.json
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Operation'
                            example:
                                status: ok
                "400":
                    description: 'invalid_url: url invalid'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /v2/pkgs/indexes/delete:
        post:
            tags:
                - indexes
            summary: remove indexes
            operationId: indexes#remove
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            url: https://downloads.arduino.cc/packages/package_index.json
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Operation'
                            example:
                                status: ok
                "400":
                    description: 'invalid_url: url invalid'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /v2/pkgs/tools/available:
        get:
            tags:
                - tools
            summary: available tools
            operationId: tools#available
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ToolCollection'
                            example:
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
    /v2/pkgs/tools/installed:
        get:
            tags:
                - tools
            summary: installed tools
            operationId: tools#installed
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ToolCollection'
                            example:
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
                                - name: avrdude
                                  packager: arduino
                                  version: 6.3.0-arduino9
        post:
            tags:
                - tools
            summary: install tools
            operationId: tools#install
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/InstallRequestBody'
                        example:
                            name: avrdude
                            packager: arduino
                            version: 6.3.0-arduino9
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Operation'
                            example:
                                status: ok
    /v2/pkgs/tools/installed/{packager}/{name}/{version}:
        delete:
            tags:
                - tools
            summary: remove tools
            operationId: tools#remove
            parameters:
                - name: packager
                  in: path
                  description: The packager of the tool
                  required: true
                  schema:
                    type: string
                    description: The packager of the tool
                    example: arduino
                  example: arduino
                - name: name
                  in: path
                  description: The name of the tool
                  required: true
                  schema:
                    type: string
                    description: The name of the tool
                    example: avrdude
                  example: avrdude
                - name: version
                  in: path
                  description: The version of the tool
                  required: true
                  schema:
                    type: string
                    description: The version of the tool
                    example: 6.3.0-arduino9
                  example: 6.3.0-arduino9
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Operation'
                            example:
                                status: ok
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                url:
                    type: string
                    description: The url of the index file
                    example: https://downloads.arduino.cc/packages/package_index.json
            example:
                url: https://downloads.arduino.cc/packages/package_index.json
            required:
                - url
        ArduinoTool:
            type: object
            properties:
                name:
                    type: string
                    description: The name of the tool
                    example: avrdude
                packager:
                    type: string
                    description: The packager of the tool
                    example: arduino
                version:
                    type: string
                    description: The version of the tool
                    example: 6.3.0-arduino9
            description: A tool is an executable program that can upload sketches.
            example:
                name: avrdude
                packager: arduino
                version: 6.3.0-arduino9
            required:
                - name
                - version
                - packager
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: url invalid
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        InstallRequestBody:
            type: object
            properties:
                name:
                    type: string
                    description: The name of the tool
                    example: avrdude
                packager:
                    type: string
                    description: The packager of the tool
                    example: arduino
                version:
                    type: string
                    description: The version of the tool
                    example: 6.3.0-arduino9
            example:
                name: avrdude
                packager: arduino
                version: 6.3.0-arduino9
            required:
                - name
                - version
                - packager
        Operation:
            type: object
            properties:
                status:
                    type: string
                    description: The status of the operation
                    example: ok
            example:
                status: ok
            required:
                - status
        ToolCollection:
            type: array
            items:
                $ref: '#/components/schemas/ArduinoTool'
            example:
                - name: avrdude
                  packager: arduino
                  version: 6.3.0-arduino9
                - name: avrdude
                  packager: arduino
                  version: 6.3.0-arduino9
                - name: avrdude
                  packager: arduino
                  version: 6.3.0-arduino9
tags:
    - name: indexes
      description: The indexes service manages the package_index files
    - name: tools
      description: The tools service manages the available and installed tools
